//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class bangdiem
    {
        public string masv { get; set; }
        public string mamonhoc { get; set; }
        public Nullable<float> diemtp { get; set; }
        public Nullable<float> diemthilan1 { get; set; }
        public Nullable<float> diemthilan2 { get; set; }
        public Nullable<float> tkmonlan1he10 { get; set; }
        public Nullable<float> tkmonlan1he4 { get; set; }
        public Nullable<float> tkmonlan2he10 { get; set; }
        public Nullable<float> tkmonlan2he4 { get; set; }
        public Nullable<float> tkmonhe10 { get; set; }
        public Nullable<float> tkmonhe4 { get; set; }
        public string tkmonhechu { get; set; }
        public Nullable<int> sotietnghi { get; set; }
        public string trangthai { get; set; }
    
        public virtual monhoc monhoc { get; set; }
        public virtual sinhvien sinhvien { get; set; }
    }
}
