//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Data.Sql;
using System.Data.SqlClient;
namespace QLSV.Data
{
    using System;
    using System.Collections.Generic;

    public class khoa
    {
        public khoa()
        {

        }

        public string makhoa { get; set; }
        public string tenkhoa { get; set; }


        public void khoaIDataReader(SqlDataReader dr)
        {

            makhoa = dr["makhoa"] is DBNull ? String.Empty : dr["makhoa"].ToString();
            tenkhoa = dr["tenkhoa"] is DBNull ? String.Empty : dr["tenkhoa"].ToString();

        }
    }
}
