//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Data.Sql;
using System.Data.SqlClient;
namespace QLSV.Data
{
    using System;
    using System.Collections.Generic;
    
    public  class lop
    {
        public lop()
        {
          
        }
    
        public string malop { get; set; }
        public string tenlop { get; set; }
        public string tenkhoa { get; set; }

        public void lopIDataReader(SqlDataReader dr)
        {

            malop = dr["malop"] is DBNull ? String.Empty : dr["malop"].ToString();
            tenlop = dr["tenlop"] is DBNull ? String.Empty : dr["tenlop"].ToString();
            tenkhoa = dr["tenkhoa"] is DBNull ? String.Empty : dr["tenkhoa"].ToString();

        }
       
    }
}
