//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Data.Sql;
using System.Data.SqlClient;

namespace QLSV.Data
{
    using System;
    using System.Collections.Generic;
    
    public  class monhoc
    {
        public monhoc()
        {
            
        }
    
        public string mamonhoc { get; set; }
        public string tenmonhoc { get; set; }
        public string tongsotiet { get; set; }
        public string sotinchi { get; set; }
        public string hocky { get; set; }

        public void monIDataReader(SqlDataReader dr)
        {
            mamonhoc = dr["mamonhoc"] is DBNull ? String.Empty : dr["mamonhoc"].ToString();
            tenmonhoc = dr["tenmonhoc"] is DBNull ? String.Empty : dr["tenmonhoc"].ToString();
            tongsotiet = dr["tongsotiet"] is DBNull ? String.Empty : dr["tongsotiet"].ToString();
            sotinchi = dr["sotinchi"] is DBNull ? String.Empty : dr["sotinchi"].ToString();
            hocky = dr["hocky"] is DBNull ? String.Empty : dr["hocky"].ToString();
        }
    }
}
