//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class monhoc
    {
        public monhoc()
        {
            this.bangdiems = new HashSet<bangdiem>();
        }
    
        public string mamonhoc { get; set; }
        public string tenmonhoc { get; set; }
        public Nullable<int> tongsotiet { get; set; }
        public Nullable<int> sotinchi { get; set; }
        public Nullable<int> hocky { get; set; }
    
        public virtual ICollection<bangdiem> bangdiems { get; set; }
    }
}
