//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinhvien
    {
        public sinhvien()
        {
            this.bangdiems = new HashSet<bangdiem>();
        }
    
        public string masv { get; set; }
        public string hoten { get; set; }
        public string malop { get; set; }
        public string ngaysinh { get; set; }
        public string diachi { get; set; }
        public string gioitinh { get; set; }
        public string tenkhoa { get; set; }
    
        public virtual account account { get; set; }
        public virtual ICollection<bangdiem> bangdiems { get; set; }
        public virtual lop lop { get; set; }
        public virtual tongket tongket { get; set; }
    }
}
