//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tongket
    {
        public string masv { get; set; }
        public Nullable<float> diemtkhe10 { get; set; }
        public Nullable<float> diemtkhe4 { get; set; }
        public Nullable<int> sotcdat { get; set; }
        public Nullable<float> diemtlky1 { get; set; }
        public Nullable<float> diemtlky2 { get; set; }
        public Nullable<float> diemtlky3 { get; set; }
        public Nullable<float> diemtlky4 { get; set; }
        public Nullable<float> diemtlky5 { get; set; }
        public Nullable<float> diemtlky6 { get; set; }
        public Nullable<float> diemtlky7 { get; set; }
        public Nullable<float> diemtlky8 { get; set; }
        public Nullable<float> diemtlky9 { get; set; }
    
        public virtual sinhvien sinhvien { get; set; }
    }
}
